use std::collections::HashMap;

#[allow(dead_code)]
pub enum HtmlElementName {
    Html,
    Base,
    Head,
    Link,
    Meta,
    Style,
    Title,
    Body,
    Address,
    Article,
    Aside,
    Footer,
    Header,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Hgroup,
    Main,
    Nav,
    Section,
    Search,
    Blockquote,
    Dd,
    Div,
    Dl,
    Dt,
    Figcaption,
    Figure,
    Hr,
    Li,
    Menu,
    Ol,
    P,
    Pre,
    Ul,
    A,
    Abbr,
    B,
    Bdi,
    Bdo,
    Br,
    Cite,
    Code,
    Data,
    Dfn,
    Em,
    I,
    Kbd,
    Mark,
    Q,
    Rp,
    Rt,
    Ruby,
    S,
    Samp,
    Small,
    Span,
    Strong,
    Sub,
    Sup,
    Time,
    U,
    Var,
    Wbr,
    Area,
    Audio,
    Img,
    Map,
    Track,
    Video,
    Embed,
    Iframe,
    Object,
    Picture,
    Portal,
    Source,
    Svg,
    Math,
    Canvas,
    Noscript,
    Script,
    Del,
    Ins,
    Caption,
    Col,
    Colgroup,
    Table,
    Tbody,
    Td,
    Tfoot,
    Th,
    Thead,
    Tr,
    Button,
    Datalist,
    Fieldset,
    Form,
    Input,
    Label,
    Legend,
    Meter,
    Optgroup,
    Option,
    Output,
    Progress,
    Select,
    Textarea,
    Details,
    Dialog,
    Summary,
    Slot,
    Template,
    Acronym,
    Big,
    Center,
    Content,
    Dir,
    Font,
    Frame,
    Frameset,
    Image,
    Marquee,
    Menuitem,
    Nobr,
    Noembed,
    Noframes,
    Param,
    Plaintext,
    Rb,
    Rtc,
    Shadow,
    Strike,
    Tt,
    Xmp
}

impl HtmlElementName {
    pub fn from_str(value: &str) -> Result<HtmlElementName, &'static str> {
        match value {
            "html" => Ok(HtmlElementName::Html),
            "base" => Ok(HtmlElementName::Base),
            "head" => Ok(HtmlElementName::Head),
            "link" => Ok(HtmlElementName::Link),
            "meta" => Ok(HtmlElementName::Meta),
            "style" => Ok(HtmlElementName::Style),
            "title" => Ok(HtmlElementName::Title),
            "body" => Ok(HtmlElementName::Body),
            "address" => Ok(HtmlElementName::Address),
            "article" => Ok(HtmlElementName::Article),
            "aside" => Ok(HtmlElementName::Aside),
            "footer" => Ok(HtmlElementName::Footer),
            "header" => Ok(HtmlElementName::Header),
            "h1" => Ok(HtmlElementName::H1),
            "h2" => Ok(HtmlElementName::H2),
            "h3" => Ok(HtmlElementName::H3),
            "h4" => Ok(HtmlElementName::H4),
            "h5" => Ok(HtmlElementName::H5),
            "h6" => Ok(HtmlElementName::H6),
            "hgroup" => Ok(HtmlElementName::Hgroup),
            "main" => Ok(HtmlElementName::Main),
            "nav" => Ok(HtmlElementName::Nav),
            "section" => Ok(HtmlElementName::Section),
            "search" => Ok(HtmlElementName::Search),
            "blockquote" => Ok(HtmlElementName::Blockquote),
            "dd" => Ok(HtmlElementName::Dd),
            "div" => Ok(HtmlElementName::Div),
            "dl" => Ok(HtmlElementName::Dl),
            "dt" => Ok(HtmlElementName::Dt),
            "figcaption" => Ok(HtmlElementName::Figcaption),
            "figure" => Ok(HtmlElementName::Figure),
            "hr" => Ok(HtmlElementName::Hr),
            "li" => Ok(HtmlElementName::Li),
            "menu" => Ok(HtmlElementName::Menu),
            "ol" => Ok(HtmlElementName::Ol),
            "p" => Ok(HtmlElementName::P),
            "pre" => Ok(HtmlElementName::Pre),
            "ul" => Ok(HtmlElementName::Ul),
            "a" => Ok(HtmlElementName::A),
            "abbr" => Ok(HtmlElementName::Abbr),
            "b" => Ok(HtmlElementName::B),
            "bdi" => Ok(HtmlElementName::Bdi),
            "bdo" => Ok(HtmlElementName::Bdo),
            "br" => Ok(HtmlElementName::Br),
            "cite" => Ok(HtmlElementName::Cite),
            "code" => Ok(HtmlElementName::Code),
            "data" => Ok(HtmlElementName::Data),
            "dfn" => Ok(HtmlElementName::Dfn),
            "em" => Ok(HtmlElementName::Em),
            "i" => Ok(HtmlElementName::I),
            "kbd" => Ok(HtmlElementName::Kbd),
            "mark" => Ok(HtmlElementName::Mark),
            "q" => Ok(HtmlElementName::Q),
            "rp" => Ok(HtmlElementName::Rp),
            "rt" => Ok(HtmlElementName::Rt),
            "ruby" => Ok(HtmlElementName::Ruby),
            "s" => Ok(HtmlElementName::S),
            "samp" => Ok(HtmlElementName::Samp),
            "small" => Ok(HtmlElementName::Small),
            "span" => Ok(HtmlElementName::Span),
            "strong" => Ok(HtmlElementName::Strong),
            "sub" => Ok(HtmlElementName::Sub),
            "sup" => Ok(HtmlElementName::Sup),
            "time" => Ok(HtmlElementName::Time),
            "u" => Ok(HtmlElementName::U),
            "var" => Ok(HtmlElementName::Var),
            "wbr" => Ok(HtmlElementName::Wbr),
            "area" => Ok(HtmlElementName::Area),
            "audio" => Ok(HtmlElementName::Audio),
            "img" => Ok(HtmlElementName::Img),
            "map" => Ok(HtmlElementName::Map),
            "track" => Ok(HtmlElementName::Track),
            "video" => Ok(HtmlElementName::Video),
            "embed" => Ok(HtmlElementName::Embed),
            "iframe" => Ok(HtmlElementName::Iframe),
            "object" => Ok(HtmlElementName::Object),
            "picture" => Ok(HtmlElementName::Picture),
            "portal" => Ok(HtmlElementName::Portal),
            "source" => Ok(HtmlElementName::Source),
            "svg" => Ok(HtmlElementName::Svg),
            "math" => Ok(HtmlElementName::Math),
            "canvas" => Ok(HtmlElementName::Canvas),
            "noscript" => Ok(HtmlElementName::Noscript),
            "script" => Ok(HtmlElementName::Script),
            "del" => Ok(HtmlElementName::Del),
            "ins" => Ok(HtmlElementName::Ins),
            "caption" => Ok(HtmlElementName::Caption),
            "col" => Ok(HtmlElementName::Col),
            "colgroup" => Ok(HtmlElementName::Colgroup),
            "table" => Ok(HtmlElementName::Table),
            "tbody" => Ok(HtmlElementName::Tbody),
            "td" => Ok(HtmlElementName::Td),
            "tfoot" => Ok(HtmlElementName::Tfoot),
            "th" => Ok(HtmlElementName::Th),
            "thead" => Ok(HtmlElementName::Thead),
            "tr" => Ok(HtmlElementName::Tr),
            "button" => Ok(HtmlElementName::Button),
            "datalist" => Ok(HtmlElementName::Datalist),
            "fieldset" => Ok(HtmlElementName::Fieldset),
            "form" => Ok(HtmlElementName::Form),
            "input" => Ok(HtmlElementName::Input),
            "label" => Ok(HtmlElementName::Label),
            "legend" => Ok(HtmlElementName::Legend),
            "meter" => Ok(HtmlElementName::Meter),
            "optgroup" => Ok(HtmlElementName::Optgroup),
            "option" => Ok(HtmlElementName::Option),
            "output" => Ok(HtmlElementName::Output),
            "progress" => Ok(HtmlElementName::Progress),
            "select" => Ok(HtmlElementName::Select),
            "textarea" => Ok(HtmlElementName::Textarea),
            "details" => Ok(HtmlElementName::Details),
            "dialog" => Ok(HtmlElementName::Dialog),
            "summary" => Ok(HtmlElementName::Summary),
            "slot" => Ok(HtmlElementName::Slot),
            "template" => Ok(HtmlElementName::Template),
            "acronym" => Ok(HtmlElementName::Acronym),
            "big" => Ok(HtmlElementName::Big),
            "center" => Ok(HtmlElementName::Center),
            "content" => Ok(HtmlElementName::Content),
            "dir" => Ok(HtmlElementName::Dir),
            "font" => Ok(HtmlElementName::Font),
            "frame" => Ok(HtmlElementName::Frame),
            "frameset" => Ok(HtmlElementName::Frameset),
            "image" => Ok(HtmlElementName::Image),
            "marquee" => Ok(HtmlElementName::Marquee),
            "menuitem" => Ok(HtmlElementName::Menuitem),
            "nobr" => Ok(HtmlElementName::Nobr),
            "noembed" => Ok(HtmlElementName::Noembed),
            "noframes" => Ok(HtmlElementName::Noframes),
            "param" => Ok(HtmlElementName::Param),
            "plaintext" => Ok(HtmlElementName::Plaintext),
            "rb" => Ok(HtmlElementName::Rb),
            "rtc" => Ok(HtmlElementName::Rtc),
            "shadow" => Ok(HtmlElementName::Shadow),
            "strike" => Ok(HtmlElementName::Strike),
            "tt" => Ok(HtmlElementName::Tt),
            "xmp" => Ok(HtmlElementName::Xmp),
            _ => Err("invalid element")
        }
    }
}

pub struct HtmlElement {
    name: HtmlElementName,
    attributes: HashMap<String, String>
}
