use std::collections::HashMap;

#[allow(dead_code)]
#[derive(Debug)]
pub enum HtmlElementName {
    Html,
    Base,
    Head,
    Link,
    Meta,
    Style,
    Title,
    Body,
    Address,
    Article,
    Aside,
    Footer,
    Header,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Hgroup,
    Main,
    Nav,
    Section,
    Search,
    Blockquote,
    Dd,
    Div,
    Dl,
    Dt,
    Figcaption,
    Figure,
    Hr,
    Li,
    Menu,
    Ol,
    P,
    Pre,
    Ul,
    A,
    Abbr,
    B,
    Bdi,
    Bdo,
    Br,
    Cite,
    Code,
    Data,
    Dfn,
    Em,
    I,
    Kbd,
    Mark,
    Q,
    Rp,
    Rt,
    Ruby,
    S,
    Samp,
    Small,
    Span,
    Strong,
    Sub,
    Sup,
    Time,
    U,
    Var,
    Wbr,
    Area,
    Audio,
    Img,
    Map,
    Track,
    Video,
    Embed,
    Iframe,
    Object,
    Picture,
    Portal,
    Source,
    Svg,
    Math,
    Canvas,
    Noscript,
    Script,
    Del,
    Ins,
    Caption,
    Col,
    Colgroup,
    Table,
    Tbody,
    Td,
    Tfoot,
    Th,
    Thead,
    Tr,
    Button,
    Datalist,
    Fieldset,
    Form,
    Input,
    Label,
    Legend,
    Meter,
    Optgroup,
    Option,
    Output,
    Progress,
    Select,
    Textarea,
    Details,
    Dialog,
    Summary,
    Slot,
    Template,
    Acronym,
    Big,
    Center,
    Content,
    Dir,
    Font,
    Frame,
    Frameset,
    Image,
    Marquee,
    Menuitem,
    Nobr,
    Noembed,
    Noframes,
    Param,
    Plaintext,
    Rb,
    Rtc,
    Shadow,
    Strike,
    Tt,
    Xmp,
    Doctype
}

impl HtmlElementName {
    pub fn to_str(&self) -> &str {
        match self {
            HtmlElementName::Html => "html",
            HtmlElementName::Base => "base",
            HtmlElementName::Head => "head",
            HtmlElementName::Link => "link",
            HtmlElementName::Meta => "meta",
            HtmlElementName::Style => "style",
            HtmlElementName::Title => "title",
            HtmlElementName::Body => "body",
            HtmlElementName::Address => "address",
            HtmlElementName::Article => "article",
            HtmlElementName::Aside => "aside",
            HtmlElementName::Footer => "footer",
            HtmlElementName::Header => "header",
            HtmlElementName::H1 => "h1",
            HtmlElementName::H2 => "h2",
            HtmlElementName::H3 => "h3",
            HtmlElementName::H4 => "h4",
            HtmlElementName::H5 => "h5",
            HtmlElementName::H6 => "h6",
            HtmlElementName::Hgroup => "hgroup",
            HtmlElementName::Main => "main",
            HtmlElementName::Nav => "nav",
            HtmlElementName::Section => "section",
            HtmlElementName::Search => "search",
            HtmlElementName::Blockquote => "blockquote",
            HtmlElementName::Dd => "dd",
            HtmlElementName::Div => "div",
            HtmlElementName::Dl => "dl",
            HtmlElementName::Dt => "dt",
            HtmlElementName::Figcaption => "figcaption",
            HtmlElementName::Figure => "figure",
            HtmlElementName::Hr => "hr",
            HtmlElementName::Li => "li",
            HtmlElementName::Menu => "menu",
            HtmlElementName::Ol => "ol",
            HtmlElementName::P => "p",
            HtmlElementName::Pre => "pre",
            HtmlElementName::Ul => "ul",
            HtmlElementName::A => "a",
            HtmlElementName::Abbr => "abbr",
            HtmlElementName::B => "b",
            HtmlElementName::Bdi => "bdi",
            HtmlElementName::Bdo => "bdo",
            HtmlElementName::Br => "br",
            HtmlElementName::Cite => "cite",
            HtmlElementName::Code => "code",
            HtmlElementName::Data => "data",
            HtmlElementName::Dfn => "dfn",
            HtmlElementName::Em => "em",
            HtmlElementName::I => "i",
            HtmlElementName::Kbd => "kbd",
            HtmlElementName::Mark => "mark",
            HtmlElementName::Q => "q",
            HtmlElementName::Rp => "rp",
            HtmlElementName::Rt => "rt",
            HtmlElementName::Ruby => "ruby",
            HtmlElementName::S => "s",
            HtmlElementName::Samp => "samp",
            HtmlElementName::Small => "small",
            HtmlElementName::Span => "span",
            HtmlElementName::Strong => "strong",
            HtmlElementName::Sub => "sub",
            HtmlElementName::Sup => "sup",
            HtmlElementName::Time => "time",
            HtmlElementName::U => "u",
            HtmlElementName::Var => "var",
            HtmlElementName::Wbr => "wbr",
            HtmlElementName::Area => "area",
            HtmlElementName::Audio => "audio",
            HtmlElementName::Img => "img",
            HtmlElementName::Map => "map",
            HtmlElementName::Track => "track",
            HtmlElementName::Video => "video",
            HtmlElementName::Embed => "embed",
            HtmlElementName::Iframe => "iframe",
            HtmlElementName::Object => "object",
            HtmlElementName::Picture => "picture",
            HtmlElementName::Portal => "portal",
            HtmlElementName::Source => "source",
            HtmlElementName::Svg => "svg",
            HtmlElementName::Math => "math",
            HtmlElementName::Canvas => "canvas",
            HtmlElementName::Noscript => "noscript",
            HtmlElementName::Script => "script",
            HtmlElementName::Del => "del",
            HtmlElementName::Ins => "ins",
            HtmlElementName::Caption => "caption",
            HtmlElementName::Col => "col",
            HtmlElementName::Colgroup => "colgroup",
            HtmlElementName::Table => "table",
            HtmlElementName::Tbody => "tbody",
            HtmlElementName::Td => "td",
            HtmlElementName::Tfoot => "tfoot",
            HtmlElementName::Th => "th",
            HtmlElementName::Thead => "thead",
            HtmlElementName::Tr => "tr",
            HtmlElementName::Button => "button",
            HtmlElementName::Datalist => "datalist",
            HtmlElementName::Fieldset => "fieldset",
            HtmlElementName::Form => "form",
            HtmlElementName::Input => "input",
            HtmlElementName::Label => "label",
            HtmlElementName::Legend => "legend",
            HtmlElementName::Meter => "meter",
            HtmlElementName::Optgroup => "optgroup",
            HtmlElementName::Option => "option",
            HtmlElementName::Output => "output",
            HtmlElementName::Progress => "progress",
            HtmlElementName::Select => "select",
            HtmlElementName::Textarea => "textarea",
            HtmlElementName::Details => "details",
            HtmlElementName::Dialog => "dialog",
            HtmlElementName::Summary => "summary",
            HtmlElementName::Slot => "slot",
            HtmlElementName::Template => "template",
            HtmlElementName::Acronym => "acronym",
            HtmlElementName::Big => "big",
            HtmlElementName::Center => "center",
            HtmlElementName::Content => "content",
            HtmlElementName::Dir => "dir",
            HtmlElementName::Font => "font",
            HtmlElementName::Frame => "frame",
            HtmlElementName::Frameset => "frameset",
            HtmlElementName::Image => "image",
            HtmlElementName::Marquee => "marquee",
            HtmlElementName::Menuitem => "menuitem",
            HtmlElementName::Nobr => "nobr",
            HtmlElementName::Noembed => "noembed",
            HtmlElementName::Noframes => "noframes",
            HtmlElementName::Param => "param",
            HtmlElementName::Plaintext => "plaintext",
            HtmlElementName::Rb => "rb",
            HtmlElementName::Rtc => "rtc",
            HtmlElementName::Shadow => "shadow",
            HtmlElementName::Strike => "strike",
            HtmlElementName::Tt => "tt",
            HtmlElementName::Xmp => "xmp",
            HtmlElementName::Doctype => "!doctype"
        }
    }

    pub fn from_str(value: &str) -> Result<HtmlElementName, &'static str> {
        match value.to_string().to_lowercase().as_str() {
            "html" => Ok(HtmlElementName::Html),
            "base" => Ok(HtmlElementName::Base),
            "head" => Ok(HtmlElementName::Head),
            "link" => Ok(HtmlElementName::Link),
            "meta" => Ok(HtmlElementName::Meta),
            "style" => Ok(HtmlElementName::Style),
            "title" => Ok(HtmlElementName::Title),
            "body" => Ok(HtmlElementName::Body),
            "address" => Ok(HtmlElementName::Address),
            "article" => Ok(HtmlElementName::Article),
            "aside" => Ok(HtmlElementName::Aside),
            "footer" => Ok(HtmlElementName::Footer),
            "header" => Ok(HtmlElementName::Header),
            "h1" => Ok(HtmlElementName::H1),
            "h2" => Ok(HtmlElementName::H2),
            "h3" => Ok(HtmlElementName::H3),
            "h4" => Ok(HtmlElementName::H4),
            "h5" => Ok(HtmlElementName::H5),
            "h6" => Ok(HtmlElementName::H6),
            "hgroup" => Ok(HtmlElementName::Hgroup),
            "main" => Ok(HtmlElementName::Main),
            "nav" => Ok(HtmlElementName::Nav),
            "section" => Ok(HtmlElementName::Section),
            "search" => Ok(HtmlElementName::Search),
            "blockquote" => Ok(HtmlElementName::Blockquote),
            "dd" => Ok(HtmlElementName::Dd),
            "div" => Ok(HtmlElementName::Div),
            "dl" => Ok(HtmlElementName::Dl),
            "dt" => Ok(HtmlElementName::Dt),
            "figcaption" => Ok(HtmlElementName::Figcaption),
            "figure" => Ok(HtmlElementName::Figure),
            "hr" => Ok(HtmlElementName::Hr),
            "li" => Ok(HtmlElementName::Li),
            "menu" => Ok(HtmlElementName::Menu),
            "ol" => Ok(HtmlElementName::Ol),
            "p" => Ok(HtmlElementName::P),
            "pre" => Ok(HtmlElementName::Pre),
            "ul" => Ok(HtmlElementName::Ul),
            "a" => Ok(HtmlElementName::A),
            "abbr" => Ok(HtmlElementName::Abbr),
            "b" => Ok(HtmlElementName::B),
            "bdi" => Ok(HtmlElementName::Bdi),
            "bdo" => Ok(HtmlElementName::Bdo),
            "br" => Ok(HtmlElementName::Br),
            "cite" => Ok(HtmlElementName::Cite),
            "code" => Ok(HtmlElementName::Code),
            "data" => Ok(HtmlElementName::Data),
            "dfn" => Ok(HtmlElementName::Dfn),
            "em" => Ok(HtmlElementName::Em),
            "i" => Ok(HtmlElementName::I),
            "kbd" => Ok(HtmlElementName::Kbd),
            "mark" => Ok(HtmlElementName::Mark),
            "q" => Ok(HtmlElementName::Q),
            "rp" => Ok(HtmlElementName::Rp),
            "rt" => Ok(HtmlElementName::Rt),
            "ruby" => Ok(HtmlElementName::Ruby),
            "s" => Ok(HtmlElementName::S),
            "samp" => Ok(HtmlElementName::Samp),
            "small" => Ok(HtmlElementName::Small),
            "span" => Ok(HtmlElementName::Span),
            "strong" => Ok(HtmlElementName::Strong),
            "sub" => Ok(HtmlElementName::Sub),
            "sup" => Ok(HtmlElementName::Sup),
            "time" => Ok(HtmlElementName::Time),
            "u" => Ok(HtmlElementName::U),
            "var" => Ok(HtmlElementName::Var),
            "wbr" => Ok(HtmlElementName::Wbr),
            "area" => Ok(HtmlElementName::Area),
            "audio" => Ok(HtmlElementName::Audio),
            "img" => Ok(HtmlElementName::Img),
            "map" => Ok(HtmlElementName::Map),
            "track" => Ok(HtmlElementName::Track),
            "video" => Ok(HtmlElementName::Video),
            "embed" => Ok(HtmlElementName::Embed),
            "iframe" => Ok(HtmlElementName::Iframe),
            "object" => Ok(HtmlElementName::Object),
            "picture" => Ok(HtmlElementName::Picture),
            "portal" => Ok(HtmlElementName::Portal),
            "source" => Ok(HtmlElementName::Source),
            "svg" => Ok(HtmlElementName::Svg),
            "math" => Ok(HtmlElementName::Math),
            "canvas" => Ok(HtmlElementName::Canvas),
            "noscript" => Ok(HtmlElementName::Noscript),
            "script" => Ok(HtmlElementName::Script),
            "del" => Ok(HtmlElementName::Del),
            "ins" => Ok(HtmlElementName::Ins),
            "caption" => Ok(HtmlElementName::Caption),
            "col" => Ok(HtmlElementName::Col),
            "colgroup" => Ok(HtmlElementName::Colgroup),
            "table" => Ok(HtmlElementName::Table),
            "tbody" => Ok(HtmlElementName::Tbody),
            "td" => Ok(HtmlElementName::Td),
            "tfoot" => Ok(HtmlElementName::Tfoot),
            "th" => Ok(HtmlElementName::Th),
            "thead" => Ok(HtmlElementName::Thead),
            "tr" => Ok(HtmlElementName::Tr),
            "button" => Ok(HtmlElementName::Button),
            "datalist" => Ok(HtmlElementName::Datalist),
            "fieldset" => Ok(HtmlElementName::Fieldset),
            "form" => Ok(HtmlElementName::Form),
            "input" => Ok(HtmlElementName::Input),
            "label" => Ok(HtmlElementName::Label),
            "legend" => Ok(HtmlElementName::Legend),
            "meter" => Ok(HtmlElementName::Meter),
            "optgroup" => Ok(HtmlElementName::Optgroup),
            "option" => Ok(HtmlElementName::Option),
            "output" => Ok(HtmlElementName::Output),
            "progress" => Ok(HtmlElementName::Progress),
            "select" => Ok(HtmlElementName::Select),
            "textarea" => Ok(HtmlElementName::Textarea),
            "details" => Ok(HtmlElementName::Details),
            "dialog" => Ok(HtmlElementName::Dialog),
            "summary" => Ok(HtmlElementName::Summary),
            "slot" => Ok(HtmlElementName::Slot),
            "template" => Ok(HtmlElementName::Template),
            "acronym" => Ok(HtmlElementName::Acronym),
            "big" => Ok(HtmlElementName::Big),
            "center" => Ok(HtmlElementName::Center),
            "content" => Ok(HtmlElementName::Content),
            "dir" => Ok(HtmlElementName::Dir),
            "font" => Ok(HtmlElementName::Font),
            "frame" => Ok(HtmlElementName::Frame),
            "frameset" => Ok(HtmlElementName::Frameset),
            "image" => Ok(HtmlElementName::Image),
            "marquee" => Ok(HtmlElementName::Marquee),
            "menuitem" => Ok(HtmlElementName::Menuitem),
            "nobr" => Ok(HtmlElementName::Nobr),
            "noembed" => Ok(HtmlElementName::Noembed),
            "noframes" => Ok(HtmlElementName::Noframes),
            "param" => Ok(HtmlElementName::Param),
            "plaintext" => Ok(HtmlElementName::Plaintext),
            "rb" => Ok(HtmlElementName::Rb),
            "rtc" => Ok(HtmlElementName::Rtc),
            "shadow" => Ok(HtmlElementName::Shadow),
            "strike" => Ok(HtmlElementName::Strike),
            "tt" => Ok(HtmlElementName::Tt),
            "xmp" => Ok(HtmlElementName::Xmp),
            "!doctype" => Ok(HtmlElementName::Doctype),
            _ => Err("invalid element")
        }
    }
}

#[derive(Debug)]
pub struct HtmlElement {
    pub name: HtmlElementName,
    pub attributes: HashMap<String, String>
}
